import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wikipida Blog App",
  description: "Generated by Tony Collins",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="bg-slate-100 dark:bg-slate-800 min-h-screen">
          <Navbar />
          {children}
      </body>
    </html>
  );
}
